### ISSUE TITLE
Challenges with High priority items overrides Nearby option.

### ISSUE THREAD

**Issue by maning** [osmlab/maproulette3#1031]
1. To test,  go to this challenge: https://maproulette.org/browse/challenges/9413
2. Select any item.
3. Change a status.
4. Choose Nearby to proceed to a new item.

Result:  Next item assigned goes to High priority items (in this case, the northern part of the Philippines).

What I expect to happen:  The nearby item should be the next task.

Other information: Manually choosing an item the map provided in the "Select your next nearby task (optional)" assigns me to the selected item.

Browser info:
Chrome 79 on MacOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36

cc @govvin

**Comment by govvin** [comment]
I confirm this behavior on Ubuntu 18.04, using Firefox v71

**Comment by nrotstan** [comment]
This is a bit of a tricky one as "nearby" is subjective, and we naturally give precedence to higher priority tasks. We may revisit in this in future, but for now I would recommend simply choosing your next task on the map if this behavior is causing you a lot of problems. I'm going to close this issue, but feel free to reopen with further discussion if you feel strongly about it.

**Comment by govvin** [comment]
![image](https://user-images.githubusercontent.com/5821688/75756242-4a709f00-5d6b-11ea-90b9-d14d4eec8f32.png)

After completing a task, a contributor is given the option of getting a random , or a nearby task. While it's true that "nearby" is subjective, the tasks presented on the map (see photo) will show what's available nearby.

Since the user already selected the nearby radio button, if no task is selected on the given map, it seems logical that a random task from whatever is available nearby should be given instead, rather than any high-priority task.

My understanding of "Select your next nearby task (optional)" is that it's optional to select one of these tasks, but if I don't select one, I'll be given one of these any way.

**Comment by nrotstan** [comment]
I don't disagree, @govvin , but this seems like an edge case to me and you're just one click away from picking your next task and avoiding the issue entirely.

I'd be happy to accept a PR if someone would like to submit one.
