### ISSUE TITLE
Make instructions visible sooner in UI hierarchy

### ISSUE THREAD

**Issue by jgscherber** [osmlab/maproulette3#1058]
When browsing for new challenges, the actual work that needs to be done (the "instructions") isn't visible until choosing to 'Start' the task. That means to decide if the work is interesting to me, I need to click twice before I can back out

![image](https://user-images.githubusercontent.com/6207661/72461594-fa2a8700-3794-11ea-82c1-7b02add8b7e0.png)

![image](https://user-images.githubusercontent.com/6207661/72461633-129aa180-3795-11ea-9925-2727689373ec.png)

**Comment by nrotstan** [comment]
Thanks for this suggestion, @jgscherber . We actually do show the description of the challenge, which is intended to help users understand what it's about and whether it's worth trying. Unfortunately, no description was provided for the challenge you mentioned above.

I think showing instructions sooner could be helpful, but it's a bit trickier than it appears at first glance because instructions are increasingly becoming customized to individual tasks (e.g. substituting OSM tag values into the instructional text) and so we'd need to decide on how to usefully and clearly display those instructions in the absence of task data.

**Comment by jgscherber** [comment]
A simple solution then maybe is to require a description for new tasks?
