### ISSUE TITLE
[request] When clearing filters, do not reset the map.

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#1064]
![image](https://user-images.githubusercontent.com/5821688/72867518-2fe1e980-3d1a-11ea-8bd2-401e0f0ecda9.png)

It's desirable to change the current behavior (resets the map) when clearing the filters while managing a task to **keep the map view**.

Right now, when I clear the filter, the map is reset to view the full challenge, but if I'm only interested in the area currently set in the view port, MR discards it, and I will have to navigate back to the area after clearing the filter.

The same thing happens anyway when I refresh the browser page (or the keyboard shortcut F5), so perhaps you could re-consider changing this behavior when clearing filters?

**Comment by nrotstan** [comment]
Thanks for the suggestion, @govvin . Can you elaborate on why you're using Clear Filters if you don't want to start over? Is it because of the Filter by Property you're showing in the screenshot?

The map is a geographic filter, so if we didn't reset it then Clear Filters wouldn't reset you back to seeing all tasks. But it doesn't sound like you're trying to start over, so maybe we just need to make some improvements that make it easier for you to clear the filters you wish to clear for what you're trying to accomplish.

**Comment by nrotstan** [comment]
MapRoulette v3.5.3 was just deployed and it includes a "Clear" button now on the property filters popup (in addition to support for [compound filters](https://github.com/osmlab/maproulette3/wiki/Challenge-Managers:-filtering-tasks-by-properties)), so hopefully that will help if it was the main issue.

**Comment by govvin** [comment]
Hi Neil. Thank you , this works for me, and the compound filters are awesome!
