### ISSUE TITLE
Getting too many "Task has already been locked by someone else." messages

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#1109]
![image](https://user-images.githubusercontent.com/5821688/74210315-2c60d300-4cc6-11ea-852f-d805c83249f7.png)

What triggers this notification? I'm pretty sure we have more than enough tasks available in our [challenge](https://maproulette.org/browse/challenges/9413), but some of our contributors in a mapathon are getting a lot of this message.

**Comment by nrotstan** [comment]
@govvin That happens when you start working on a task that someone else is already working on. The server won't typically serve up tasks that are already locked, though, so it doesn't sound right that you're running into it a lot. Are mappers just completing tasks normally, or finding tasks to work on some other way?

Also, that looks like MapRoulette v3.5.3. We deployed v3.5.4 earlier today, so you might try refreshing your browser if you're still seeing v3.5.3 (the version is in the footer).

**Comment by govvin** [comment]
They are working on tasks normally, either randomly or nearby.  This is the first time we encountered this, which is unusual.

I'll check out the new version! Thanks.

**Comment by nrotstan** [comment]
I'm going to close this issue, but feel free to reopen if it continues to be a problem.
