### ISSUE TITLE
React error and page crash: "An `id` must be provided to format a message." when viewing a task

### ISSUE THREAD

**Issue by impiaaa** [osmlab/maproulette3#1293]
```
Invariant Violation: "[React Intl] An `id` must be provided to format a message."
    exports browser.js:38
    be index.es.js:804
    value index.es.js:1630
    React 11
        Oo
        So
        To
        Fa
        Ba
        Os
        xs
        ys
        Ga
        enqueueSetState
        setState
    Redux 4
        onStateChange
        f
        r
        dispatch
    se Task.js:190
react-dom.production.min.js:198:194
    React 7
        ra
        callback
        Ko
        Xo
        Ra
        Da
        Es
    unstable_runWithPriority scheduler.production.min.js:18
    React 7
        Es
        Os
        xs
        ys
        Ga
        enqueueSetState
        setState
    Redux 4
        onStateChange
        f
        r
        dispatch
    se Task.js:190
```

Example task (not the same one as the error): https://maproulette.org/challenge/13834/task/56849498

Example entry from the source GeoJSON (not the same as either of the above):
```json
{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "properties": {
                "osm_id": "node/6949608627",
                "wd": "http://www.wikidata.org/entity/Q8027",
                "wdLabel": "Martin Luther King Jr."
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -122.2771481,
                    37.8049507
                ]
            }
        }
    ],
    "cooperativeWork": {
        "meta": {
            "version": 2,
            "type": 1
        },
        "operations": [
            {
                "operation": "modifyElement",
                "data": {
                    "id": "node/6949608627",
                    "operations": [
                        {
                            "operation": "setTags",
                            "data": {
                                "name:etymology:wikidata": "Q8027"
                            }
                        }
                    ]
                }
            }
        ]
    }
}
```

**Comment by nrotstan** [comment]
Thanks for reporting this, @impiaaa ! The actual crash looks to be related to a bug surfacing an error message, which we'll get fixed.

But the error itself is due to a problem with the operation structure, which looks to be a result of a mistake in our documentation. If you change `"operation": "modifyElement",` to `"operationType": "modifyElement",` I think that will address the problem (the setTags operation is fine). I will get our documentation fixed as well -- sorry about that :-(

You can use the Rebuild Tasks control when managing the challenge to upload fresh GeoJSON (on the dialog that pops up, use the option to first delete incomplete tasks).

Did you create this challenge by hand, or did you use the [mr-cli](https://www.npmjs.com/package/@maproulette/mr-cli) tool?

**Comment by impiaaa** [comment]
> Did you create this challenge by hand, or did you use the [mr-cli](https://www.npmjs.com/package/@maproulette/mr-cli) tool?

By hand, or rather with a little CLI script.

I'll try `operationType` when I can. Thanks!
