### ISSUE TITLE
link "approved source of external data" to import guidelines

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/maproulette3#1316]
https://wiki.openstreetmap.org/wiki/Import/Guidelines

I can make a PR - which language file is a base for translations and should be modified?

**Comment by mvexel** [comment]
I think we should trust authors of challenges to be familiar enough with OSM that they know how to proceed with external data. Linking to the import guidelines can be misleading because we cannot assume that any data would actually be imported; that is up to the mapper in the end. So for now, we won't link to the import guidelines, but I am happy to be convinced otherwise with a good argument.
