### ISSUE TITLE
Compact Mode / Collapse top nav

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#1388]
On smaller screens the top nav and challenge info elements take up 1/3 or more of screen real estate.

1920x1080:

![image](https://user-images.githubusercontent.com/120452/93535533-63563180-f904-11ea-9798-c4d4c1e8710b.png)

1360x768:

![image](https://user-images.githubusercontent.com/120452/93535689-b9c37000-f904-11ea-9ff3-6dbedab75751.png)

Wed analytics tell us that these are among the most used display resolutions among MR users.

To give users more screen real estate when working on tasks, I propose introducing the ability for users to collapse the top part of the UI to something like this:

![image](https://user-images.githubusercontent.com/120452/93537073-c72e2980-f907-11ea-9add-f14e04e197a7.png)

**Comment by Binnette** [comment]
I'm affected by this bug too :+1: 
Here is a screenshot of my whole screen
![image](https://user-images.githubusercontent.com/6597721/98288918-cdf02900-1fa7-11eb-87c9-9693841a7a38.png)

I can't see the location map on the left without scrolling. And i can't see the whole map :wink: 

So each time, I want to solve a challenge, I need to scroll a bit...

**Comment by nrotstan** [comment]
Thanks for the feedback, @Binnette ! We do have plans for a more compact header, but it's only going to save a certain amount of space.

I would recommend using the "Edit Layout" button near the top-right to resize the map and other widgets -- and to rearrange them as well -- so that everything best fits your screen and working style (hopefully without too much scrolling). You can even save multiple layouts and switch between them, if desired.

Here is a [document](https://learn.maproulette.org/documentation/using-layouts/) about customizing your layout.

**Comment by nrotstan** [comment]
The compact workspace header is now on maproulette.org
