### ISSUE TITLE
Tasks Failed to Build with remote GeoJSON

### ISSUE THREAD

**Issue by jbelien** [osmlab/maproulette3#1414]
Hello, I'm trying to create a new challenge using a remote GeoJSON but I get "_Tasks Failed to Build_" every time (see details below).
The weird thing is that each time I go in "_Edit Challenge_" the source is set as "_I want to provide an Overpass query_" (instead of "_I have a URL to the GeoJSON data_").

Is there something wrong with my GeoJSON file (it seems correct and open in QGIS and https://geojson.io/ without any issue) ?

The challenge is `14645`.
I tried the following 2 URLs for the GeoJSON file (same file) ([preview](https://github.com/osmbe/road-completion/blob/master/data/belgium/flanders/difference/Wegenregister_SHAPE_20200917/diff.geojson)):
- <https://github.com/osmbe/road-completion/raw/master/data/belgium/flanders/difference/Wegenregister_SHAPE_20200917/diff.geojson>
- <https://raw.githubusercontent.com/osmbe/road-completion/master/data/belgium/flanders/difference/Wegenregister_SHAPE_20200917/diff.geojson>

Thanks a lot for your help!

**Comment by nrotstan** [comment]
Hi @jbelien , thanks for reporting this! It looks like the server is having trouble downloading remote GeoJSON. We're looking into it.

As a work-around, you can of course download the geojson yourself and create your challenge from the local file (though you'll have to repeat that process if you wish to update the tasks in the future with updated geojson data). I tested the file and the GeoJSON itself is fine.

Also, just as an FYI, that first URL is no good -- it actually returns HTML instead of the geojson. But the second one (raw.githubusercontent.com) is fine.

**Comment by jbelien** [comment]
Thanks for looking into this!

> As a work-around, you can of course download the geojson yourself and create your challenge from the local file (though you'll have to repeat that process if you wish to update the tasks in the future with updated geojson data).

That's indeed what I did but it will be easier to just click the "_Rebuild Tasks_" button. 🤩 

> Also, just as an FYI, that first URL is no good -- it actually returns HTML instead of the geojson. But the second one (raw.githubusercontent.com) is fine.

Noted! 👌

**Comment by nrotstan** [comment]
Remote GeoJSON should be working now on maproulette.org, @jbelien . Thanks again for the report!

**Comment by jbelien** [comment]
Awesome, it works!
Thanks @nrotstan \o/
