### ISSUE TITLE
What is the preferred method for reporting MR challenges?

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/maproulette3#1461]
For example, undiscussed imports, importing data of unknown copyright status.

EDIT: this specific case is not requiring for now any actions like that, but I want to know how this is handled once situation repeats.

**Comment by nrotstan** [comment]
Challenges have a link to contact the challenge owner (just underneath the challenge title if you start the challenge).

**Comment by matkoniecz** [comment]
> Challenges have a link to contact the challenge owner (just underneath the challenge title if you start the challenge).

I already contacted the challenge owner (via Polish forum). But I was trying to check whatever there is moderation of any kind on MR and who and how should be contacted.

**Comment by mvexel** [comment]
@matkoniecz there is no built in arbitration on the MapRoulette platform. If mappers are demonstrably putting in objectively bad data, reporting specific changesets to DWG would be the next step. If the problem can be traced back to a poorly designed Challenge, we can work with them to determine next steps.

**Comment by matkoniecz** [comment]
So moderation/taking down MR tasks happens solely on DWG request and unless someone is from DWG they should not contact MapRoulette operators about that?

**Comment by mvexel** [comment]
See my previous comment. We're always willing to work via the established channels to deal with data issues, and we have in the past.

**Comment by SomeoneElseOSM** [comment]
> We're always willing to work via the established channels to deal with data issues, and we have in the past.

Come on Martijn, that's a bit disingenuous.  "challenges" such as https://maproulette.org/browse/challenges/16438 are clearly just an attempt to "gruntwash" an automated edit.  Regardless of whether changing "facebook" tags to "contact:facebook" or vice versa is a good idea or not, an edit such as that is subject to https://wiki.openstreetmap.org/wiki/Automated_Edits_code_of_conduct and shouldn't be suggested by sites such as this in good faith.

It's a shame, because there's lots of genuinely useful stuff at https://maproulette.org/dashboard .

> Challenges have a link to contact the challenge owner (just underneath the challenge title if you start the challenge).

For completeness the data edits in the above challenge weren't reported to us, but the one behind https://twitter.com/richardf/status/1363909152582627328 was.  In this case, however, there seems to be no way to contact the challenge owner.  How do I contact the user who created https://maproulette.org/browse/challenges/16122 ?

**Comment by matkoniecz** [comment]
>  How do I contact the user who created https://maproulette.org/browse/challenges/16122 ?

You can 

- go to https://maproulette.org/browse/projects/42733 
- select still open https://maproulette.org/browse/challenges/16995
- press start, going to https://maproulette.org/challenge/16995/task/84260189
- press three dot menu button
- select "contact challenge owner"
- what allows to send message to user with id 77904 ( "Kristjan ESPERANTO" )

![screen02](https://user-images.githubusercontent.com/899988/109375982-8b898980-78c1-11eb-9c0d-c7e6ac15d9ea.png)

Method above will not work if all challenges are closed in a given project.

> an edit such as that is subject to https://wiki.openstreetmap.org/wiki/Automated_Edits_code_of_conduct

It was not clear to me. Would it be OK to add explicit "asking people to replace all instances of one tag with another, for example by creating a  MapRoulette challenge, is also a form of automated edit"?

>  Regardless of whether changing "facebook" tags to "contact:facebook" or vice versa is a good idea or not

And MapRoulette had both "move facebook to contact:facebook" and "remove contact: prefix" when I checked days ago.

**Comment by matkoniecz** [comment]
I found https://learn.maproulette.org/documentation/reporting-a-challenge/ while I was looking for something different
