### ISSUE TITLE
User have a lot of challenges without single task

### ISSUE THREAD

**Issue by idenkov** [osmlab/maproulette3#1480]
Hello,

I just found a user that have a lot of challenges and most of them does not have a single task - https://maproulette.org/browse/projects/1141

Can this be fixed or make it so users can't have challenges without a task?

**Comment by nrotstan** [comment]
Hi @idenkov , thanks for the report! All of the challenges I clicked on in that project seem have tasks, though there are thousands of challenges in it. Can you point out which challenges you're referring to specifically?

I will also note that that because there are so many challenges in that project, it takes a while for the project-level stats to load on that project page. We could probably do a better job of indicating that.

**Comment by idenkov** [comment]
Hi @nrotstan 

Thanks for the reply, you are right I see a lot of projects with tasks, but also here are some examples when I try to search for challenges including "Bulgaria"
https://maproulette.org/browse/challenges/4664
https://maproulette.org/browse/challenges/4662
https://maproulette.org/browse/challenges/4660
https://maproulette.org/browse/challenges/4661

There is much more, but it will be better not to spam. 
I was wondering if it is possible to do something like `DELETE FROM challenges WHERE task=0`
Or not allowing empty challenges, it seems that user added this programmatically but something went wrong for part of them.

I just thought things like these might put off some people trying to complete challenges - if they see long lists of spam.

Thanks!

**Comment by nrotstan** [comment]
Ah, thanks, @idenkov , I think these challenges are using Overpass queries that are no longer returning any results. We should probably be automatically setting them to Finished status in that case so they don't show up in search results. Related to #986.

**Comment by nrotstan** [comment]
PR maproulette/maproulette2#867 will address this going forward, automatically marking challenges as finished if there are no remaining tasks following an Overpass rebuild.
