### ISSUE TITLE
Staging site doesn't display tasks with proposed changes correctly.

### ISSUE THREAD

**Issue by atiannicelli** [osmlab/maproulette3#1497]
I am working on staging.maproulette.com (version 3.7.0) and I imported a challenge with tasks that have proposed changes. These task look correct on the production site, but on the staging site I get an error when displaying a task with proposed changes. 

Error: "Oops! Failed to load cooperative task: undefined" 

Here is an example of a task where I see the issue: https://staging.maproulette.org/challenge/4196/task/12475434

**Comment by nrotstan** [comment]
Hi @atiannicelli , the staging MR server points to the dev OSM server (https://master.apis.dev.openstreetmap.org), so you'll need to make sure your OSM data exists there in order to do a cooperative challenge on staging. That way there's no risk of inadvertently corrupting production OSM data when changes are submitted.
