### ISSUE TITLE
Allow challenge creators to set the default layout

### ISSUE THREAD

**Issue by boothym** [osmlab/maproulette3#1509]
If the instructions for a task are too long, a scroll bar appears. When editing the layout you can drag the corner to make the widget bigger. However that only affects your own layout.

It would be good if the challenge creator could set a default layout, in terms of widgets visibility, size and location, for any users to the challenge who don't already have a layout set.

This would also help with #1492 so that two background widgets could be set by default.

**Comment by nrotstan** [comment]
Since layouts can be exported and imported, you could simulate this today by adding a link to a recommended layout in your challenge instructions and letting mappers know they can import it if desired. You could also highlight at the top of your instructions that they're long and to please read in full to the bottom.

It's worth noting that MapRoulette users make use of a large variety of screen sizes, from 13" laptops to dual wide-screen displays, and it's very challenging to create a single layout that works optimally for everyone. We have also found that experienced users like to add a lot of widgets as they get more comfortable with MapRoulette, whereas newer users find dense layouts to be overwhelming and confusing.

These are the main reasons why we support customizable layouts and even allow multiple layouts to be configured and saved (e.g. one for the dual-monitor setup at home and one for the 13" screen on the go), plus the bonus of being able to create a personalized workspace of course. The default layout is aimed at newer users and intended to function on smaller screens.

It might still be interesting to let challenge managers attach a recommended layout and offer that to mappers as an option, but I suspect such functionality would be most useful when some kind of niche widget is particularly useful to solve some type of challenge, and even then the challenge creator can always simply recommend use of that widget in their challenge instructions.

**Comment by mvexel** [comment]
Good discussion. The workarounds @nrotstan mentions are reasonable, and we could do a better job pointing to / creating relevant documentation (created a new label for this). Since it's hard to predict exactly what the MR will look like on a mapper's screen, as Neil also mentioned, I think this is not something we will want the challenge author to be able to set, since it would give them a sense of control they really do not have over the screen layout, and may lead to unpleasant surprises for unsuspecting mappers. The import / export function will be a good workaround.
