### ISSUE TITLE
Allow changing overpass query

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/maproulette3#1563]
I will need to change link (to exclude some elements), but it appears to require creating new challenge what will break incoming links (see #890)

Would it be possible to allow changing Overpass query after challenge creation?

Or is there some workaround (maybe always generate challenge from data allowing to change query)?

**Comment by mvexel** [comment]
Hi @matkoniecz. Unfortunately, this is not possible by design. Your best bet is to clone the challenge, but you would indeed need to provide people with a new URL to the Challenge.

One "workaround" would be to use Overpass Turbo to export the Overpass result as GeoJSON and use that to create the challenge. You *can* replace the data in a GeoJSON based Challenge.

**Comment by matkoniecz** [comment]
> Unfortunately, this is not possible by design.

And I guess that is some important assumption somewhere and not reasonably fixable?

**Comment by mvexel** [comment]
You are correct, this is not a behavior that would be easy to change.
