### ISSUE TITLE
Make challenges invisible after six months

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#1580]
In an effort to keep tasks fresh and weed out challenges that are abandoned by their owners, we plan to automatically make challenges invisible 6 months of their creation date. The challenges affected will merely hidden and deleted: owners can easily make them visible again, and mappers who know the URL can still work on them, but they will not show up on search or the map until they are made visible again.

We will also require owners to have an email address on file so we can send out notifications and otherwise engage more with owners to ensure tasks are fresh. #1543

**Comment by jschwarz2030** [comment]
Updated Proposed Tech Requirements:

1. Create a scheduler that analyzes challenges’ updatedDate columns.  If over 6 months, drill down to the tasks to see if any of them have been worked on.  If not, archive the challenge.  As a possible performance improvement, if a task has been updated recently, update the challenge updatedDate column with the same time as that task so that the scheduler doesn’t need to drill down to the tasks again.
2. Alert the challenge creator via email perhaps a week prior challenge is archived so that they have a chance to update the stale challenge
3. On the Challenge search page, filter out archived challenges initially, but add a toggle to the page that allows the user to see/not see archived challenges alongside.

**Comment by jschwarz2030** [comment]
In regards to tech requirement 2, I think it's wise to implement the notification system in a separate rollout from this feature. 
 The reason is, the initial bulk-archive job will be substantially larger than its subsequent runs, since the system will be playing catch up.  Perhaps a community announcement would be sufficient.  After that, we can provide notifications for challenges most recently becoming stale.
