### ISSUE TITLE
Tag fix Task should not be created / displayed if no tag changes present

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#1647]
See https://maproulette.org/challenge/21846/task/106166961

![Screenshot_20210910_134850](https://user-images.githubusercontent.com/120452/132909656-186ae037-dab1-4233-a91f-d4806cc3bd7d.png)

If there are no tag changes, the task makes no sense.

**Comment by atiannicelli** [comment]
@mvexel I found out the cause of this issue. The original tag change proposal was to remove the `railway=level_crossing` tag. But it seems that someone already removed that tag from the feature. So it was created correctly, but the feature has changed since we scanned and the tag we wanted to remove is now gone. I would think in this case I guess it would just be best to not display the "Proposed OSM tag Changes" if there are none to display and the user can mark it as "already fixed"
