### ISSUE TITLE
Editing a campaign after cloning shows the wrong form

### ISSUE THREAD

**Issue by tordans** [osmlab/maproulette3#1690]
1. I cloned a campaign which lead me to this URL https://maproulette.org/admin/project/47245/challenge/24053?filters.metaReviewStatus=0%2C1%2C2%2C3%2C5%2C6%2C7%2C-2&filters.priorities=0%2C1%2C2&filters.reviewStatus=0%2C1%2C2%2C3%2C4%2C5%2C6%2C7%2C-1&filters.status=0%2C1%2C2%2C3%2C4%2C5%2C6%2C9&boundingBox=-198.63281250000003%2C-38.54816542304657%2C85.078125%2C69.77895177646761&cloneChallenge=true&includeTags=false&page=0&pageSize=20&refreshAfterSave=true&sortCriteria.direction=DESC&sortCriteria.sortBy=name&zoom=2 – Screenshot 1
 2. When I click Edit, I get to https://maproulette.org/admin/project/47245/challenge/24053/edit, but see the clone page. <<- This is the error – Screenshot 2

However, while writing this issue I noticed, that
1. Edit Clicking Edit on https://maproulette.org/admin/project/47245/challenge/24053
2. Does show the right form at https://maproulette.org/admin/project/47245/challenge/24053/edit

It looks like, that the URL I had open has a param which changes the content of the edit page?

Screenshot 1:
<img width="540" alt="Bildschirmfoto 2022-01-06 um 11 14 46" src="https://user-images.githubusercontent.com/111561/148367979-195ca208-c26e-4c2e-9cf6-c2c54b916e6c.png">

Screenshot 2:
<img width="1207" alt="Bildschirmfoto 2022-01-06 um 11 16 53" src="https://user-images.githubusercontent.com/111561/148368050-be9ff797-b8ce-46f7-aedb-1ff5605b4e51.png">

**Comment by jschwarz2030** [comment]
This issue is evading me.  I've been trying to reproduce locally using the following steps:

1. create challenge
2. on challenge dashboard page, click "Clone"
3. on edit page, provide a new name and click "Next" and "Finish"
4. on the new challenge dashboard page, click "Edit" - takes me to the Edit page.

This will work properly every time.  I did notice your url filters above include `cloneChallenge=true`.  Even if I manually add your filters to my test challenge url, and then click "Edit", it doesn't reproduce the issue.

Do you have any additional information on what steps you're taking to create this issue, and is it happening regularly?

Thanks for reporting this!

**Comment by tordans** [comment]
Thanks for looking into this, @jschwarz2030. I will close this for now and come back in case I see it again.

**Comment by danieldegroot2** [comment]
@jschwarz2030 Could you try to abandon a clone and then edit the original challenge? May be browser-dependent.

Editing a challenge with an (abandoned) clone points to the (abandoned) clone

**Expected behaviour**
MR brings you to the edit screen for the challenge itself, not its (abandoned) clone

**How to reproduce**
1. Create Challenge
2. Clone Challenge
3. Abandon Challenge while creating challenge clone
(there is no clone displayed in the create & manage screen btw, this is working correctly)
4. Edit Challenge -which you abandoned creating a clone of-
5. MR brings you back to the Create Challenge screen for the (abandoned) clone..

(Refreshing seems to inconsistently fix this so it brings you to the regular edit screen again)

Browser: Chrome
