### ISSUE TITLE
Undo Marked Task Accidentally

### ISSUE THREAD

**Issue by adiatmad** [osmlab/maproulette3#307]
Could I undo a marked task by accidentally? I found only "Next/Previous Task" button when try to reach it back. Thanks

**Comment by mvexel** [comment]
Hi @adiatmad -- you could use the browser back button to reach previous tasks. 

You can also use the API to see tasks you worked on recently, `http://maproulette.org/api/v2/data/user/activity?limit=100` (you need to be authenticated for that, call it from a browser session where you are signed in to the MapRoulette application).

**Comment by adiatmad** [comment]
Hi @mvexel 
1. I am noticing some situations:
I mark task as "I Fix It" & "Already fixed" accidentally, then I use the browser back button to reach previous tasks, no "Edit" button shows to complete it again.
But when I mark task as "Not an issue" accidentally, the "Edit" button still show when I am reach it back.
More complete button available when I reach back after hit "Skip".
It would be great if we could edit again the task that marked fix accidentally rather than find-download manually via JOSM. 

2. API ways
It is very clear as you explain. I have no more question about this. Thank you very much.

**Comment by nrotstan** [comment]
I'm reopening this issue. It's easy to inadvertently click the wrong task-completion control (or use the wrong keyboard shortcut) and submit an incorrect task status, and there is not currently any confirmation of submission, nor obvious way to undo the mistaken submission from the next task. As @mvexel mentions, you can hit the browser Back button and attempt to fix the status, but our strict status-progression rules don't allow some statuses to be freely changed once set.

One option is to add a confirmation step when a user selects a completion status, prior to submitting the status, to help catch mistaken clicks/presses. Another option would be to leave submission as is and add an "undo" option from the next task, probably in the form of a status bar or something that indicates the user successfully marked the prior task as X along with an undo control.

My personal inclination is to lean towards the undo, as it doesn't impose an additional step on everyone, but a confirmation step is certainly easier to add.

It's worth noting that neither of these would automatically address the situation of realizing later that a series of tasks were submitted with the wrong status due to, say, a misunderstanding of statuses. But the undo functionality would obviously get us closer to that if we wished to offer something down the road.

**Comment by nrotstan** [comment]
We now offer a confirmation step after choosing a task status, with a cancel option if the wrong status was inadvertently chosen.
