### ISSUE TITLE
Are tasks that include attributes that could be merged with OSM feature possible?

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#425]
If my memory serves me right, I thought it was possible to do this in an earlier version of MapRoulette.

With MR3, is there a way to send the task data to OSM?

Use case:
We have been allowed by the local department of education to add their school database to OSM. Some data may not exist yet, and we're allowed to add them. For others, we'd like to add details that are not yet in OSM.

**Comment by nrotstan** [comment]
The earlier version did have an option allowing you to view the raw GeoJSON for a task. Is that perhaps what you're referring to?

**Comment by nrotstan** [comment]
Oops, hit wrong button, didn't mean to close.

**Comment by govvin** [comment]
@nrotstan 

No, not that.

I was thinking whether it's stillpossible to send data to the editor when the task is opened, for possible conflation into OSM. For example, addr:*=* tags coming from the geojson file?

**Comment by mvexel** [comment]
this would have to be done through JOSM remote control. I don't know if we did something like this before, actually. This may be supported through the `addtags` remote control parameter. I'd like to understand the use case a little bit better, though. 

Say you have a school node from an external source. It already exists in OSM. What would the task be?

This use case may be covered by #367

**Comment by mvexel** [comment]
I like this use case and I want to explore it further. 

It looks to me like there are two avenues to implementing this:
1. The '[Suggested Fixes](
https://github.com/osmlab/maproulette3/issues/367)' feature that has been in the works for a while. This would enable the challenge owner to create tasks that have a built-in fix that mappers can verify and apply directly in MapRoulette without going into an editor at all. Since MapRoulette is not and does not aspire to be an OSM editor, this would be a 'yes or no' option -- either you accept the tag / geometry change and it gets applied to OSM, or you don't.
2. Use the JOSM remote control `[load data](https://josm.openstreetmap.de/wiki/Help/RemoteControlCommands#load_data)` or `[add_node]` and `[add_way]` commands ([examples](https://josm.openstreetmap.de/wiki/Help/RemoteControlCommands#addtags)). The challenge owner would need to encode and add the URL parameter to the task. Obviously this is limited to JOSM and we would need to add a way to identify challenges as 'JOSM only'.

We are already working on option 1, but it will be limited to adding / changing tags only for the moment. Later we will extend the feature to geometries, but it's very unlikely to involve editing the geometry before committing it. That is why I still like option 2 as an alternative / less advertised feature; the changes to MapRoulette could be limited; a very minimal implementation would just add a JOSM URL parameter to the challenge definition. 

More discussion needed.

**Comment by govvin** [comment]
Thank you for the updates, @mvexel .

For the use case I have in mind, the task data may not always have the better information (e.g. location, attribute), but it's also possible that they haven't been added to OSM at all.

Visual validation can help determine whether the data can be (a) merged with existing data (and mark as done) ;  (b) create a new element (at least a node, better as a polygon) with the basic attributes included;  (c) mark as unverifiable/cannot fix;

Ilya Zverik's [auditor](http://audit.osmz.ru) conflator takes an interesting approach to conflating data, by allowing the user to choose which data to add, without launching any editor
![image](https://user-images.githubusercontent.com/5821688/51520960-15073b80-1e60-11e9-886a-4d8bf6065b55.png)

**Comment by mvexel** [comment]
The auditor is interesting but it's entirely unclear to me what happens if you push any of the buttons. That is potentially dangerous as people make inadvertent changes to OSM because they don't know how the application works. Perhaps this is just me, but I think this application needs a lot of work to be a good OSM citizen. As it is, I can see it being useful for experienced OSM editors, but not for a more general, on average less experienced mapping public -- which is who we're targeting with MapRoulette. Every action you take on MapRoulette should be 100% clear in its consequences (what happens when I press this / do that). This becomes even more important as MapRoulette ventures into altering OSM directly. This is something we take very very seriously (which is also part of the reason why it's not done yet).

So back on topic :) I think OSM can support visual validation in in two ways:
* We already have the option of switching aerial / map layers. Challenge owners can set the preferred layer for their challenge and even add a custom TMS endpoint.
* Mapillary integration (later OSC also) is coming #563 

We need to do more to support visual validation, like
* highlight its geometry on the map and any changes that would be applied (in an Achavi-like way)
* visualize changes in tags. The color scheme used by auditor is good (green for new, yellow for changed, red for deleted) but it needs to be side by side (an example of good visualization is Deep History, see screenshot below)

<img width="714" alt="screenshot 2019-01-28 10 38 10" src="https://user-images.githubusercontent.com/120452/51854817-f46c3500-22e8-11e9-80c9-d82c24b3039e.png">

**Comment by nrotstan** [comment]
The first iteration of [quick fixes](https://github.com/osmlab/maproulette3/wiki/Creating-Quick-Fix-Challenges) (a.k.a suggested fixes) is now available and supports adding additional tags to OSM elements via MapRoulette tasks.
