### ISSUE TITLE
Refresh challenges

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#430]
Currently MapRoulette does not make it very clear if / how challenges are updated as the task source data updates. There are three possible scenarios

## Local GeoJSON
Currently does not allow re-uploading. 

Ideally, we'd allow re-uploading with the understanding that any task that cannot be matched with an already present task ID (OSM ID? Other field) will be added as a new task, and currently present tasks that do not appear in the new file, will be marked as done. We'd need to decide on what uniquely identifies a task.

## Remote GeoJSON
Currently: ?? 

Situation is similar to Local GeoJSON, but there would need to be a trigger for re-checking the remote URL. Perhaps this can be set in the challenge creation process (re-check every...) or there could be a 'refresh' option on the main challenge admin screen.

## Overpass
Currently: ??

Similar to Remote GeoJSON, there could be a setting in the challenge admin to automatically re-check the Overpass query. Added difficulty is that the only thing we'd have to go on for the unique identifier would be the OSM ID.

**Comment by nrotstan** [comment]
I think this is a great idea. Currently we allow refreshing only from Overpass, as we're guaranteed to get back OSM ids that we can use to reconcile against existing tasks and reduce the chances of accidental mass task duplication. Refreshes are requested manually by the challenge owner.

Looking ahead, we can refresh local and remote GeoJSON as long as ids are provided. Probably the simplest thing would be to check the original GeoJSON for ids and, if present, mark the challenge as "refreshable". Refreshable challenges could be refreshed with updated GeoJSON files as long as the new files also contain ids. We'd display the same warning to challenge owners that we currently do when manually refreshing from Overpass.

For Overpass and Remote GeoJSON (with ids), we would also support optional scheduling of automatic refreshes.

**Comment by Noki** [comment]
@nrotstan great that you want to add this feature! Can't wait to see it done.

Please also have a look at #251 when you start working on this. It would really help to be able to have a single auto refreshing global phone and fax number challenge in the future and when you work on this, it would probably be the foundation for that. 

Just to give you an idea about the problem:

![image](https://user-images.githubusercontent.com/198902/48100419-746f8b00-e223-11e8-9ed6-e0503502faaf.png)

My challenges dashboard is really messed up. I haven't rebuild any challenges lately because It would probably take me an hour or more to rebuild them all and from previous experience I know that rebuilding multiple of them at the same time results in the rebuilds to fail.

**Comment by nrotstan** [comment]
PR #527 in combination with server PR maproulette/maproulette2#437 adds support for rebuilding challenges from local or remote GeoJSON (in addition to Overpass, which was already supported). It also adds a new option to remove unmatched incomplete tasks prior to the rebuild, providing a mechanism for cleaning up stale tasks that no longer need to be addressed. A [wiki page](https://github.com/osmlab/maproulette3/wiki/Rebuilding-(Updating)-Challenge-Task-Data) with an explanation of the feature has also been added.

Future work:
* Detect lack of feature ids in GeoJSON that is likely to lead to task duplication
* Support scheduled refreshes for remote and overpass sources
* Support "global" challenges (#251) once implemented

**Comment by nrotstan** [comment]
I've broken out the future work discussed above into new issues and am closing this one.
