### ISSUE TITLE
When changing default editor in user profile, UI resizes

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#437]
After using the dropdown in the user profile to change default editor, the UI resizes and becomes wider, no longer fitting in the window. This happens again when repeating the action, each time stretching the UI more. 

Chrome (latest stable) on Mac High Sierra.

**Comment by nrotstan** [comment]
The root cause of this is actually a bug on the server that is causing the encrypted form of the API key to be re-encrypted on each update, leading to longer and longer keys (and thus a wider API key box on the UI, causing the resizing behavior). I'll be fixing the UI so that it won't continue growing wider, but the server issue will need to be addressed as well. I've opened issue #442 to track it.
