### ISSUE TITLE
When a Task contains a Point as well as a Linestring, make sure the Point lies within the viewport

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#451]
Consider task http://maproulette.org/mr3/challenge/367/task/367271 

Upon initial load, depending on zoom level, the marker for the Point may lie outside the viewport, since the Linestring is long.

The Point likely indicates the location that needs attention.

So we should make sure the Point is always visible in the viewport as the task is loaded.

**Comment by nrotstan** [comment]
Clicking the "crosshairs" icon on the right side to fit the map to the task features does include the point on that task, as expected.

So I think the problem here is our preservation of the zoom level moving from task to task within a challenge: we should only preserve the zoom if all the features of the new task will be displayed on the map at that zoom level, otherwise we should automatically fit the map to the task features.
