### ISSUE TITLE
"Fit task to map bounds" option

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#528]
For challenges where the 'size' of the task can vary quite a bit, it can be hard to define a default zoom level for the challenge.

Can we add something like a 'fit to map' option where the map bounds would adapt to the task geometry, limited by the minimum and maximum zoom level set by the challenge author?

**Comment by nrotstan** [comment]
Fitting the map to the taks was default behavior, originally, but we changed it to preserve the user's zoom level from the prior task as they moved to the next task (and added the cross-hairs control to the map that would re-fit the map to the task when clicked).

Rather than making the decision for the user, maybe we just need to offer this as a "More Options" switch setting during task completion -- "always fit map to task" or something -- which could also be influenced by a challenge setting, as suggested.

**Comment by mvexel** [comment]
Right, sorry for going back and forth on this. I do think the 'fit to map' as a default does make more sense in some cases, so it should probably be a challenge setting.

Case where it makes a lot of sense: A Challenge that has various linestring features with varying lengths.
Case where it doesn't make so much sense: A Challenge that has point features only. Here you'd assume that the user tweaks the zoom level to fit their default.

**Comment by nrotstan** [comment]
Closing due to age.
