### ISSUE TITLE
expecting user management in main project view

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#534]
The adding / managing of Project owners / managers is somewhat hidden in the project list. I was looking for it in the main Project view. Would it make sense to move it there?

**Comment by nrotstan** [comment]
UI/UX: We need to design what this would look like. Right now administration of project managers occurs in the Create section from a "Managers" tab on a project card (it's not available in list view nor from search results). I can see the argument for making this a separate widget, but it also means it'll be necessary to somehow convey which project is being administrated since it won't be associated with a project like it is currently.

The existing design is also just something I created during implementation, so it probably needs to be revisited anyway.

<img width="433" alt="manager_admin" src="https://user-images.githubusercontent.com/445970/49823962-c0878100-fd35-11e8-96e3-d0d837b28d1e.png">

**Comment by mvexel** [comment]
See also #622 

I can see a widget in the Project detail screen that provides the functionality of adding / removing Managers.
