### ISSUE TITLE
When editing the Challenge, do not rebuild tasks

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#573]
When I make a small edit to a challenge, say a typo in the description, I do not want MR to rebuild the tasks necessarily. This can take a long time and incur unnecessary load on Overpass as well as the MR server. Also not needed since we have separate 'rebuild' option.

**Comment by mvexel** [comment]
It doesn't seem to do this always.. If you click 'finish' after editing something on screen 1 it doesn't, for example.

**Comment by rivermont** [comment]
Alternatively, instead of disabling the functionality entirely, a switch could be added to rebuild after editing.  
I would argue that it should be turned off by default as minor edits that don't require a rebuild are likely more common than those that do.

**Comment by mvexel** [comment]
I think this is no longer done when you press the 'finish' button after editing. @nrotstan correct? (if so please close :))

**Comment by jbelien** [comment]
> I think this is no longer done when you press the 'finish' button after editing.

I got the issue today with a remote GeoJSON file : it rebuild all my tasks when I just changed the "Challenge Basemap".
That's a bit problematic since all the tasks are duplicated because of that.

**Comment by nrotstan** [comment]
Thanks for the feedback, @jbelien . I recommend making sure your tasks have some kind of unique id property so that they don't get duplicated on rebuilds. You can read more about that on the [Learn](https://learn.maproulette.org/documentation/setting-external-task-identifiers) site.

In the mean time, you can try doing another rebuild ("Rebuild Tasks" button) and choosing the option to first delete all incomplete tasks, which will hopefully remove your dups.

As far as this specific issue is concerned, we've gotten better, but some changes do still result in unnecessary rebuilds. Typically this is an inconvenience, though, rather than an outright problem.

**Comment by jbelien** [comment]
> I recommend making sure your tasks have some kind of unique id property so that they don't get duplicated on rebuilds. You can read more about that on the Learn site.

Good to know ; I'll check if I could implement that easily.

> In the mean time, you can try doing another rebuild ("Rebuild Tasks" button) and choosing the option to first delete all incomplete tasks, which will hopefully remove your dups.

Yes, definitely not an issue, I already did that twice. 👍

**Comment by grischard** [comment]
This also bit me.

Could there be an option to generate the unique IDs based on the geojson attributes, including coordinates?

**Comment by mvexel** [comment]
You mean some sort of hash based on the location and properties combined? I think theoretically that could be done. However, I wouldn't want to take the option to have your own unique IDs away from the user. So it would need to be a fallback. 

We'll look into this more, but in the mean time, let's see if we can do a better job educating the user about the importance of having unique identifiers for your tasks.
