### ISSUE TITLE
Custom basemap URL instructions incorrectly suggest that you need to escape curly braces

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#575]
In fact, escaping curly braces in the URL will not yield the desired result and the basemap will not load.

![image](https://user-images.githubusercontent.com/120452/49887548-e5ddc300-fdf9-11e8-83f3-dbcac07eb992.png)

**Comment by nrotstan** [comment]
Thanks, the backslashes shouldn't be there. Their appearance looks to be caused by bug yahoo/react-intl#1158 in the internationalization library we're using. It works correctly in development mode (no backslashes) but not in production mode. I'll see if we can come up with a workaround until that bug is fixed.
