### ISSUE TITLE
failed to upload files and create a task

### ISSUE THREAD

**Issue by JLZIMMERMANN** [osmlab/maproulette3#647]
I have already tried to push a geoJSON and Maproulette displays that it failed to create the task

> JsResultException(errors:List((,List(JsonValidationError(List(error.expected.jsobject),WrappedArray())))))

https://maproulette.org/mr3/admin/project/757/challenge/3637

The files I tried to push were first attempt with polygone and then another one with centroids
These files are here
https://we.tl/t-og6yUrAPB1

Regards

Jean-Louis

**Comment by nrotstan** [comment]
Hi @JLZIMMERMANN, thanks for the report! The polygon file fails because you have some null geometries. That is technically legal geojson, but MapRoulette doesn't support it. There's some discussion of this in #551 -- we need to handle the situation better.

The centroid file worked for me. If you're still running into problems with it, can you note the error you're seeing?

**Comment by JLZIMMERMANN** [comment]
Hello Neil,

Thanks for your answer. If you have been able to rebuild it could you share
this task with me and put me in admin @JLZIMMERMANN
I tried to rebuild the task but I only have this



[image: image.png]
Regards,

Jean-Louis

**Comment by nrotstan** [comment]
Unfortunately that image didn't come through, but you can manage the centroids challenge I created here: https://maproulette.org/mr3/admin/project/3447/challenge/3698

I made you an admin. You'll obviously need to edit the challenge and set it up with a name, description, instructions, etc. Neither the challenge nor project is currently visible.
