### ISSUE TITLE
Tip to increase the editing area and decrease the amount of tasks

### ISSUE THREAD

**Issue by raphaelpe** [osmlab/maproulette3#683]
Good Morning, 

A suggestion to increase the editing area and decrease the amount of tasks, with this change the task completion time would increase and it would be concluded faster!

This is the suggestion for development team!

Strong hug

Raphaelmirc

**Comment by nrotstan** [comment]
Hi @raphaelpe, if you are referring to the size of the map on the task-completion page, you can click the Edit Layout button and customize the layout. You can move around the various widgets, resize them (making the map bigger) or even remove some widgets entirely.

<img width="511" alt="editlayout" src="https://user-images.githubusercontent.com/445970/54132982-78c6d300-43d2-11e9-96bf-87e8ba993994.png">

Let me know if you were talking about something else.

**Comment by raphaelpe** [comment]
Hello Neil Rotstan, and this option of tasks, only that I tried to delete and also decrease the amount of tasks but I could not, it would be good if the size of the mapping area was larger and with fewer tasks to facilitate the completion of the task completely in 100%.

**Comment by raphaelpe** [comment]
good afternoon nrotstan, help me? I tried deleting the widgets but I can not, what do I do? I click edit but I can not delete it!

**Comment by nrotstan** [comment]
Hi @raphaelpe, I'm adding an animated gif showing me making the map bigger and changing the layout of the task-completion page. I move the other widgets from the left side of the map to the bottom of the map. I did not delete any widgets, but you could do so by clicking the red "Delete Widget" button at the top-right corner of the widget once you have started editing the layout. A couple of widgets willl not have a "Delete Widget" button because they cannot be deleted, as they are required for task completion (for example the map itself and the Completion widget that contains the Edit and other task-completion buttons).

Let me know if I'm misunderstanding what you are trying to do.

![ExpandTaskMap](https://user-images.githubusercontent.com/445970/54791984-7007a580-4bf9-11e9-966a-b312f0bfdbf5.gif)

**Comment by raphaelpe** [comment]
the night nrotstan!

it would not be that option you show in the gif, because the size of the map on the maproulette site is good,


What I say would be the amount of the tasks as shown in the image below.
![Tarefa maproulette - 1](https://user-images.githubusercontent.com/6382348/54794013-297b7080-4c24-11e9-9358-1578f7003122.jpg)


the second image shows how it should be a single task, as it would help to finish the tasks quickly.
![mudar a tarefa para que seja uma tarefa unica - 22](https://user-images.githubusercontent.com/6382348/54794119-955dd900-4c24-11e9-9f47-e6d16f7e7323.jpg)


these tasks should be one, as shown in the image it is difficult to finish a task set with various tasks
![mudar essa opçao para facilitar o termino da tarefa - 3](https://user-images.githubusercontent.com/6382348/54794161-c807d180-4c24-11e9-8b3a-fa555fa01f74.jpg)


when the other options on the site are all working perfectly, what I ask would be an improvement in this aspect of many tasks and the difficulty of finishing the tasks created for a city,

**Comment by nrotstan** [comment]
Ah, I see. The individual tasks are determined by the person creating the challenge, although when creating a challenge from an Overpass query each result will automatically become a task. In general, MapRoulette is made for fixing small, isolated tasks individually rather than trying to complete a lot of stuff in a geographic area as one big task. We do offer a setting in a "More Options" widget that lets users work on nearby tasks instead of random ones, so that a user can easily move from task to task in a single city or region. We will be making that setting more prominent in an upcoming release, but for now you will need to add the "More Options" widget when completing a task to get access to that setting, and then indicate you wish to load tasks by "Proximity"

<img width="423" alt="moreoptions" src="https://user-images.githubusercontent.com/445970/54836227-07640b80-4c81-11e9-862b-57f9f95d0357.png">

<img width="521" alt="proximity" src="https://user-images.githubusercontent.com/445970/54836502-93763300-4c81-11e9-8ac8-7eb740a9a460.png">

**Comment by raphaelpe** [comment]
good night nrotstan, I understand more I hope an update will be made to improve the completion of great tasks.

**Comment by raphaelpe** [comment]
made the modification and improved the tasks, but gave developers an option to create larger areas in the street name edition.

**Comment by raphaelpe** [comment]
good afternoon nrotstan, 
wanted an example of the overpass to change of address of the schools, the city and Recife, Pernambuco, Brazil. can you send me

**Comment by mvexel** [comment]
Hi @raphaelpe -- the best place to get help with Overpass questions is at help.osm.org . 

I'll close the issue here but if you have additional MapRoulette related bug reports or feature requests feel free to open another issue.

Thanks!
