### ISSUE TITLE
New challenge has invalid "tasks from" date

### ISSUE THREAD

**Issue by nrotstan** [osmlab/maproulette3#684]
Challenge created from an Overpass query in the last 24 hours is missing a date for the last task refresh.

https://maproulette.org/browse/challenges/3846

**Comment by mvexel** [comment]
The last 24 hours since you posted the issue or 24 hours from challenge creation?
The challenge you link to above still has an invalid date there.

**Comment by DavidMetcalfe** [comment]
Since the linked challenge results in "That challenge does not exist," here are some more with Invalid Date.

https://maproulette.org/browse/challenges/9344
https://maproulette.org/browse/challenges/9248
https://maproulette.org/browse/challenges/9207
https://maproulette.org/browse/challenges/8861

All the ones I'm finding thus far are by "andrewwiseman" in case that helps narrow down the cause.

**Comment by nrotstan** [comment]
I believe this has been fixed. Feel free to reopen if not.
