### ISSUE TITLE
Only 400 tasks showing up out of 5601 line upload

### ISSUE THREAD

**Issue by typicalTYLER** [osmlab/maproulette3#701]
I uploaded this file: https://gist.github.com/typicalTYLER/4b1c71cee219b566cf5d670a88a5aee5 as a geoJSON defining a challenge, and only 400 tasks showed up after 2 hours. I'll check back again in the morning and delete this issue if it shows all the tasks. Here's the challenge https://maproulette.org/admin/project/3749/challenge/4013

**Comment by typicalTYLER** [comment]
Still only 400 are showing up after 11 hours.

**Comment by nrotstan** [comment]
Hi @typicalTYLER, it looks like we have a bug where the upload progress isn't being displayed properly for line-by-line geojson uploads, but your file does upload properly in my tests and creates all the tasks if the upload isn't interrupted. My guess is that you inadvertently interrupted the upload since no progress was displayed. Once interrupted, no more tasks will be created.

I'd give it another try and, just to be safe, wait 5 mins after clicking "Finish" when creating the challenge before trying to see how many tasks were created. I'll take a look at fixing the progress display bug.

Let me know if you still have trouble, and thanks for the report!

**Comment by typicalTYLER** [comment]
Thanks! Rebuilding and uploading the file again seemed to work. I think maybe the whole system was overloaded at the time as I was experimenting with other large overpass queries and making tasks based off of them. Thanks for your help!

Follow up q: Do I need to rebuild tasks for the priority rules I set up afterward to take effect?

**Comment by typicalTYLER** [comment]
Also I'm still having trouble uploading geojson files every once in a while, it'll hang at 0 tasks uploaded for a really long time, and then eventually I'll click out of the window, and then an hour or so later my task will only have 130 or so tasks remaining and I'll have to rebuild again. And now whenever I try to access the task I get a 504 error.

**Comment by nrotstan** [comment]
@typicalTYLER the fix for upload progress not displaying was deployed to maproulette.org on Wednesday, which should help with the issue you experienced.
