### ISSUE TITLE
Let users view how other set Challenges

### ISSUE THREAD

**Issue by yt9tp** [osmlab/maproulette3#721]
For novice users it would be tremendous help if they could see how other users set their challenges. There is no better way to learn but from working examples.

**Comment by nrotstan** [comment]
Thanks for bringing this up, @yt9tp. We can definitely do a lot more to make challenge creation easier. Are there specific aspects or settings that you're interested in?

**Comment by yt9tp** [comment]
Actualy I had few issues to understand.

1. I wanted to create challenge that selects some highway way objects for naming. Ways did not show up in chalenge until I included nodes too. I ended up with challenge with frightening number of tasks as all nodes were counted too althrough those are not meant to be edited at all.

2. Resolving tasks did not show up in challenge until I updated tasks with option to delete. That messed up with perspective what was included in challenge at start and what has been done, as, after each refresh only unresolved tasks were left.

3. I have to run tasks update manually to see what has been done so far, as already resolved objects kept coming up.

4. For number of highways there were several sections to edit. Each section is represented with tasks, actually number of task because task is created for each node on way. But, tasks were not offered in logical order (for example all tasks related to a single way i na row) but almost completely random across al ways. ti makes things harder to do as each next task ends up on a totally new way. It is much easier to edit road by road (all tasks in one road and then move to all tasks in other road).


It might be I did not understand how all this works. I tried to find and read all instructions available.

**Comment by mvexel** [comment]
Hi @yt9tp -- I do understand it could be  easier, and documentation easier to find. [This](https://www.openstreetmap.org/user/mvexel/diary/46863) is probably the most comprehensive guide out there to help with Challenge creation. 

A couple of points to your questions:
* To avoid getting way-nodes as separate tasks, use `[out geom]` instead of recurse down in your Overpass query. This will get you the way geometry without the nodes as separate objects. See [here](https://overpass-turbo.eu/s/IaA) for an example of how to not do it and [here](https://overpass-turbo.eu/s/IaB) for a fixed example.
* MapRoulette is designed to have randomly assigned tasks by default, but users can override it to receive 'nearby' tasks instead. As a Challenge owner, you could encourage mappers to use that, if it's relevant to your challenge. You could also try pre-processing the task GeoJSON to group tasks that you think belong together logically.

We're always happy to help, so let us know if you have any trouble.

**Comment by yt9tp** [comment]
Thanks.

I followed your suggestion abutusing [out geom]. Change in GeoJSNO is visible and it is now more logical - nodes are part of ways. However. Maproulette still counts nodes as tasks and for each way I have to go through each node.

It is now even more obvious when I use option to get next task in near. Getting near tasks works fine, except that most near tasks are nodes that do not need editing at all.

**Comment by yt9tp** [comment]
I got it. I had to remove clause

(._;>;);

Without it i could not get any task before. Now, after I set [out geom] just selecting ways works fine and result contains only ways, without nodes. Excellent!

Thanks a lot!

As I cannot edit Overpass query it seems I have to create new chalenges and delete those that I used so far.

**Comment by mvexel** [comment]
Yes, you need to delete the old challenge and start a new one, sorry.

**Comment by mvexel** [comment]
I am going to close this because the OP's specific questions were answered, and we have #96 to cover documentation.
