### ISSUE TITLE
Minimize the need to sign in

### ISSUE THREAD

**Issue by maxerickson** [osmlab/maproulette3#722]
It would be nice to be able to do as much as possible on the site without signing in. Even editing doesn't really require signing in, just have separate buttons for open in iD and open with remote control. That won't generate user statistics, but so what.

I get that it's a ux choice, I don't see why an open data project would require sign in just to browse around.

**Comment by mvexel** [comment]
Currently you can already do quite a bit without authentication -- discovering challenges, viewing tasks. I don't believe that OSM authentication is an unusual burden for OSM related QA and editing software. 

Requiring authentication for operations that modify the  MapRoulette database makes it much easier for us to keep MapRoulette vandalism / abuse free, and that improves the experience for everybody. 

Looking ahead to future development, specifically #367 which we are implementing right now, OSM authentication is required regardless, since we'd be accessing parts of the OSM API that require it.
