### ISSUE TITLE
OAuth sign-in is not remembered

### ISSUE THREAD

**Issue by SilentSpike** [osmlab/maproulette3#765]
It seems like every browser restart I have to re-sign in which means my OSM account has a large amount of tokens issued to MapRoulette (see screenshot below). It would be nice if this wasn't the case.

![image](https://user-images.githubusercontent.com/5459452/58515461-d0d4d080-819c-11e9-97c7-74634a0915d4.png)

**Comment by mvexel** [comment]
If we stored the oauth access keys on the server, we'd have to associate them with a user, meaning we'd have to have actual local user accounts which is something we've been trying to avoid. If you don't clear cookies / local storage for maproulette.org, you should not have to re-authenticate.

**Comment by SilentSpike** [comment]
🤔 I haven't cleared cookies/local storage in a long time

**Comment by zerebubuth** [comment]
I think this might be due to the default setting of the Scala Play [session cookies](https://www.playframework.com/documentation/2.7.x/SettingsSession#Session-Timeout-/-Expiration). Specifically, unless `play.http.session.maxAge` is overridden, the default instructs the browser to clear the cookie when the window is closed, logging us out.

If the desired behaviour is not re-authenticating each time, then the value could be changed to a longer time (e.g: `7 days`) in [`conf/application.conf`](https://github.com/maproulette/maproulette2/blob/master/conf/application.conf). However, changing it in the source might be annoying to override for development environments and so forth (where logging out might be the desired behaviour). If there's a deployment config repo somewhere, perhaps I could submit a PR there?

**Comment by mgcuthbert** [comment]
Hey @zerebubuth I would point you to this file https://github.com/maproulette/maproulette2-docker/blob/master/api/docker.conf where you can create a PR and add this value. This is the file that we use for any values to override, as you can see is also later modified with secrets and keys, but if you add it there we should be able to get the value in a future deployment.

**Comment by zerebubuth** [comment]
@mgcuthbert that's great, thanks!

**Comment by mvexel** [comment]
https://github.com/maproulette/maproulette2-docker/pull/30 should mitigate this to the extent that we want it to :)
