### ISSUE TITLE
add option to create a tasks list

### ISSUE THREAD

**Issue by JLZIMMERMANN** [osmlab/maproulette3#843]
The idea is on this twitter post https://twitter.com/JLZIMMERMANN/status/1157581095141085184?s=20

![image](https://user-images.githubusercontent.com/4929752/62490886-cb15ef80-b7ca-11e9-89ab-02f6e5436009.png)
My idea is that when I have an area that is too big to review and check I need a way to be able to progress even the task is too big. A way would be to give ability to create a tasks list that would give ability to progress step by step.
We have such option in trello 
![image](https://user-images.githubusercontent.com/4929752/62491044-3233a400-b7cb-11e9-9016-a94209e175a5.png)

**Comment by mvexel** [comment]
Hi @JLZIMMERMANN -- thanks for the suggestion. Is it possible to use the existing comments field for this? So if somebody fixes one part of the task, they can add a comment to the task and Skip it. The next person then can look at the comments and see what still needs to be done.

Since the goal for MapRoulette is to provide simple, quick tasks for people to fix, having a full-fledged sub-task list for each task feels antithetical.. I think if a task becomes so complex that subtasks are needed, perhaps you could consider splitting the challenge into multiple separate challenges, or use Tasking Manager instead.

Please let us know your thoughts.

**Comment by JLZIMMERMANN** [comment]
I think it would be really great if it could be a **widget** for specific challenges.

**Comment by JLZIMMERMANN** [comment]
In Trello we are able to add a lot of features like in the picture 
![image](https://user-images.githubusercontent.com/4929752/62495950-c572d680-b7d7-11e9-8886-76c2f36b618b.png)

**Comment by mvexel** [comment]
Thanks. I will leave this issue open for more discussion, but I do think that it goes against the idea of MapRoulette offering *simple* tasks. If a task becomes complicated enough to involve several discrete steps that need to be resolved, then I think they should either be broken up into different challenges, or perhaps Tasking Manager would become a better tool for this type of task.

**Comment by nrotstan** [comment]
We now support customizable [form templates](https://github.com/osmlab/maproulette3/wiki/Task-Completion-Forms-Templates) that can be setup in the challenge instructions. This isn't exactly the same thing, but may be useful when the challenge creator knows ahead of time that some kind of checklist would be helpful during task completion.

**Comment by nrotstan** [comment]
Closing this issue as we support for the form templates.
