### ISSUE TITLE
Maproulette should use a specefic field as feature id

### ISSUE THREAD

**Issue by britiger** [osmlab/maproulette3#952]
I'm currently create a webpage (see https://github.com/britiger/bikeparkingberlin/) where you can compare bike parking in OSM with OpenData. So I get a list of missing objects, there doesn't exists in OSM. Every dataset has different columns. I created an export to geojson with all columns. These columns also named `id` or `name` like the dataset of jena ([Jena.json.txt](https://github.com/osmlab/maproulette3/files/3746453/Jena.json.txt)). According to https://github.com/osmlab/maproulette3/wiki/Rebuilding-(Updating)-Challenge-Task-Data Maproulette should use the property `id` as feature id in Maproulette for updates without deleting all incomplete tasks. But after creating task it always uses `name` in this example. There could be duplicated names so if I set the same name to all features I only get one task. But if I rename `id` to `name` property Maproulette don't use this property and generates a own feature id.
Another problem is, if I have a propertiy `id` with numeric part maproulettes parses this as a node-id for osm. This sometimes ends up with an 404 error if the node-id doesn't exists when opening the task with the iD editor.

Is it possible to get put an `id` field into geojson which always used which do not interprets this data as an OSM-object id?

**Comment by nrotstan** [comment]
Thanks for bringing this up, @britiger. The current situation is a bit incoherent and we do need to do a better job with it. There are a few related, but separate, issues:

1. Properly identifying OSM ids in task properties. Right now this is MapRoulette's top priority and it will look at all of those properties mentioned on that wiki page. Most (but not all) MapRoulette tasks target existing OSM elements, so matching up OSM ids is very important so that the user experience (and editing experience) is as expected.

2. Identifying duplicate tasks during a challenge rebuild/refresh so that tasks are properly replaced with updated data rather than mass duplicated. Again, most MR tasks target OSM elements so a properly-identified OSM id will serve this purpose, but we also will look at things like a `name` property if we need to.

3. Displaying a recognizable task identifier to users, especially challenge creators, but also mappers for scenarios like #951 . For most tasks targeting OSM elements, the OSM id is the desired identifier, but not always -- sometimes challenges revolve around named entities (like businesses or schools) and the challenge creator would rather see tasks identified by those names. On the other hand, a challenge could be for different locations of the same business and the name is worthless to users as an identifier, but maybe the address would be good. We need to offer flexibility to the challenge creator.

Originally, `name` was interpreted as the "external" or "private" id you ask about, and is what was displayed to users as the task identifier. But as people began to recognize it as the displayed unique identifier they started putting their OSM ids there when they had them, especially as a lot of people would consider "way/123456789" to be the name they wish to see for a task targeting an OSM way. And so at some point we started looking for OSM ids in the name field to ensure we picked up on them. This definitely has muddied the waters, especially as name is an OSM tag and often appears in feature properties as a result, and led in part to our current situation that you are bringing up.

As a side note, MapRoulette will also look for these properties on the feature itself in addition to the properties, providing challenge creators with a way to "override" the feature properties. Originally, we actually only looked for names and ids on the feature itself (and ignored the feature properties), but as users began putting names and ids in various places we started looking at properties too, especially once we began supporting rebuilding/refreshing challenges as it became very important for us to be able to identify tasks using only what was availabile in the GeoJSON to avoid duplicating them. That decision to look at properties has also added to the confusion.

So looking ahead, there are a number of things we desire:
1. An easily identifiable OSM id for tasks targeting OSM elements
2. A "private" or "external" id for challenge creators who wish to provide one, which will not be confused with an OSM id nor other properties or OSM tags, but could be used by MapRoulette during challenge rebuild/refresh to ensure tasks are properly updated and not duplicated
3. A meaningful identifier to show users, which may be an OSM id, may be represented by a different property (like name), may be the external id, or may be something different altogether
4. Compatibility with identifiers used by Overpass, which is used to generate a lot of challenges
5. All of these things without risks of conflicts or confusion, that will be applied in an obviously deterministic manner so that challenge creators can easily understand how everything will be interpreted
6. The final solution needs to be (mostly) backward compatible, as there are users who create challenges through the API using tools that would break

**Comment by nrotstan** [comment]
Given that Overpass uses `@id` to provide OSM identifiers, I propose we go with that as the default OSM id field, but we also allow challenge creators to optionally specify a field to use instead (the name of which would be recorded on the challenge). This provides flexibility while eliminating guesswork, and it also serves as a backward-compatible solution as we could scan existing challenges with our current logic and record which field we're picking up that represents OSM ids (if any).

We could take the same approach for an external id field. I'd suggest `externalId` (or `@externalId` if we want to stick with an `@` theme) as a default, so that it's explicit.

Finally, we could support an option for specifying which field/property to use as a human-readable task identifier appropriate for the challenge (e.g. `@id`, `name`, `brand`, `tiger:NAME`, etc.). We could also support references to multiple properties via mustache tags, such as`{{addr:housenumber}} {{addr:street}}`, which would be more flexible, but I propose we wait on that -- we can always support it later in a future iteration, if needed, and it's likely to constrain our ability to support other features related to display names.

Feedback welcome, as always.

**Comment by tordans** [comment]
@nrotstan it sounds like right now there is a lot of magic happening and – with all magic – this is too hard to understand. I also understand your last message the way, that you plan to make this magic more explicit, right? IMO this would be the way to go! To have a config somewhere that makes it explicit which fields should be used for what.

Is this something someone is going to work on in the coming month?

For the issue @britiger and I have, what would be the easiest way to work around the current magic? We don't have any OSM ids in our source data, so my understanding is we need to make sure that the current system does not interpret any data as OSM-ids, right? Do you see a way to do this?

**Comment by nrotstan** [comment]
@tordans The short answer is yes, you should be able to work around the issue. It will be potentially easier after v3.5.4 is deployed to maproulette.org this next week, but should still be possible today.

In an earlier release we started verifying that the osm id we have for a task actually looks like an OSM id before we send it off to editors, so the issue of random UUIDs being sent to iD or JOSM should be fixed. Note, however, that we only perform that check when trying to *use* the osm id, and it does not affect the "magic" scanning process of deciding which property field to treat as osm ids -- that's solely based on the presence of the property.

The upshot is that, while a bit of a hack, you can put unique non-osm ids into a osm id field and everything should still work normally (and those ids won't be sent to editors as long as they don't look like OSM ids). For example, you could generate unique UUIDs for each feature and put them onto an `id` field and MR will use those instead of continuing to scan and picking up your (non-unique) `name` fields. If you also need a specific external id for conflation or something that would otherwise be confused with an osm id, you could store them on an additional property. 

So something like:
```json
{
  "type": "Feature",
  "properties": {
    "id": "43062222-772d-4e49-ac1e-2c66ad3d7dbc",    <-- unique UUID 
    "externalId": 1,                                 <-- external id for conflation
    "building": "yes",
    "name": "Some Building",
  },
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        [
          -120.1870532,
          48.4797882
        ],
        [
          -120.1870683,
          48.4797215
        ],
        [
          -120.1868969,
          48.4797045
        ],
        [
          -120.1868818,
          48.4797712
        ],
        [
          -120.1870532,
          48.4797882
        ]
      ]
    ]
  }
}
```


In v.3.5.4 we allow challenge creators to specify which feature property to treat as an OSM id, so you can choose your own name for your UUID (or whatever) field and skip the magic scanning process altogether. The [wiki page](https://github.com/osmlab/maproulette3/wiki/Challenge-Managers:-setting-external-task-IDs-(e.g.-OSM-IDs)) has been updated to discuss this new option.

##### Some other notes:

* When looking at the tasks table for a challenge in Create & Manage, it's possible to configure which columns you see (and their order), including seeing feature properties. So you could show your `externalId` and even hide the "feature id" (UUID) column if desired. Note that sorting by property columns isn't supported, so it's a little bit more limited, but may still be useful

* You can also, during challenge creation, configure specific properties to be included in CSV exports. A future version will likely align the CSV export with whatever columns you've configured on your tasks table so it won't be necessary to configure it during challenge creation, but that isn't in yet. Still, if you want `externalId` to be included in CSV exports, you can edit the challenge and set that up

* GeoJSON exports always preserve all of your properties and don't need any additional setup

* When rebuilding tasks, MR will look at the `id` column (in the example above), so it's important those ids stay consistent for a given feature if you rebuild tasks with updated data

Let me know if you still run into issues.

**Comment by tordans** [comment]
Thanks for the help @nrotstan, we will continue to experiment :-).
